language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
install:
  - gem install aws-sdk-core
  - gem install clap
  - gem install cutest -v 1.1.3
  - gem install codeclimate-test-reporter
script:
  RUBYLIB=./lib cutest test/*_test.rb
